Doctolib/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;



    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column (nullable: true)]
    private ?bool $is_medecin = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_clinique = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $clinique_adresse = null;

    #[ORM\ManyToMany(targetEntity: Specialite::class, inversedBy: 'users')]
    private Collection $Specialite;

    #[ORM\ManyToMany(targetEntity: Commentaire::class, inversedBy: 'users')]
    private Collection $Commentaire;

    #[ORM\Column(nullable: true)]
    private ?int $favoris = null;

    #[ORM\Column (nullable: true)]
    private ?bool $rdv = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Rendezvous $Rendezvous = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Sexe $Sexe = null;

    public function __construct()
    {
        $this->Specialite = new ArrayCollection();
        $this->Commentaire = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function isIsMedecin(): ?bool
    {
        return $this->is_medecin;
    }

    public function setIsMedecin(bool $is_medecin): self
    {
        $this->is_medecin = $is_medecin;

        return $this;
    }

    public function getNomClinique(): ?string
    {
        return $this->nom_clinique;
    }

    public function setNomClinique(?string $nom_clinique): self
    {
        $this->nom_clinique = $nom_clinique;

        return $this;
    }

    public function getCliniqueAdresse(): ?string
    {
        return $this->clinique_adresse;
    }

    public function setCliniqueAdresse(?string $clinique_adresse): self
    {
        $this->clinique_adresse = $clinique_adresse;

        return $this;
    }

    /**
     * @return Collection<int, Specialite>
     */
    public function getSpecialite(): Collection
    {
        return $this->Specialite;
    }

    public function addSpecialite(Specialite $specialite): self
    {
        if (!$this->Specialite->contains($specialite)) {
            $this->Specialite->add($specialite);
        }

        return $this;
    }

    public function removeSpecialite(Specialite $specialite): self
    {
        $this->Specialite->removeElement($specialite);

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaire(): Collection
    {
        return $this->Commentaire;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->Commentaire->contains($commentaire)) {
            $this->Commentaire->add($commentaire);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        $this->Commentaire->removeElement($commentaire);

        return $this;
    }

    public function __toString()
    {
        return $this->prenom;
    }

    public function getFavoris(): ?int
    {
        return $this->favoris;
    }

    public function setFavoris(?int $favoris): self
    {
        $this->favoris = $favoris;

        return $this;
    }

    public function isRdv(): ?bool
    {
        return $this->rdv;
    }

    public function setRdv(bool $rdv): self
    {
        $this->rdv = $rdv;

        return $this;
    }

    public function getRendezvous(): ?Rendezvous
    {
        return $this->Rendezvous;
    }

    public function setRendezvous(?Rendezvous $Rendezvous): self
    {
        $this->Rendezvous = $Rendezvous;

        return $this;
    }

    public function getSexe(): ?Sexe
    {
        return $this->Sexe;
    }

    public function setSexe(?Sexe $Sexe): self
    {
        $this->Sexe = $Sexe;

        return $this;
    }

}

Doctolib/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('roles')
            ->add('password')
            ->add('isVerified')
            ->add('nom')
            ->add('prenom')
            ->add('adresse')
            ->add('is_medecin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

Doctolib/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\User1Type;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        $users = $userRepository->findAll();
        return $this->render('user/index.html.twig', [
            'users' => $users,
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $form = $this->createForm(User1Type::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(User1Type::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }

    public function addFavoris(User $user, EntityManagerInterface $em)
{
    $user->setFavoris($user->getFavoris() + 1);
    $em->persist($user);
    $em->flush();

    return $this->redirectToRoute('app_user_show', ['id' => $user->getId()]);
}

}

Doctolib/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

Doctolib/templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Doctolib/templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
<div class="container mt-5">
<div class="card">
<div class="card-header bg-primary text-white text-center py-3">
<h3>Edit User</h3>
</div>
<div class="card-body">
{{ include('user/_form.html.twig', {'button_label': 'Update'}) }}
            <div class="d-flex justify-content-center">
                {{ include('user/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

Doctolib/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Liste des utilisateurs</h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 10px">#</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Adresse</th>
                <th style="width: 40px">Medecin</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.isVerified ? 'Yes' : 'No' }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.adresse }}</td>
                <td>{{ user.isMedecin ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_user_new') }}">Create new</a>
{% endblock %}

Doctolib/templates/user/medecin.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
<div class="container mt-5">
<div class="card">
<div class="card-header bg-primary text-white text-center py-3">
<h3>User Profile</h3>
</div>
<div class="card-body">
<table class="table table-striped">
<tbody>
<tr>
<th>Email</th>
<td>{{ user.email }}</td>
</tr>
<tr>
<th>Nom</th>
<td>{{ user.nom }}</td>
</tr>
<tr>
<th>Prenom</th>
<td>{{ user.prenom }}</td>
</tr>
<tr>
<th>Adresse</th>
<td>{{ user.adresse }}</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
{% endblock %}

Doctolib/templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

Doctolib/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block body %}
<div class="container mt-5">
<div class="card">
<div class="card-header bg-primary text-white text-center py-3">
<h3>Information</h3>
</div>
<div class="card-body">
<table class="table table-striped">
<tbody>
<tr>
<th>Email</th>
<td>{{ user.email }}</td>
</tr>
<tr>
<th>Nom</th>
<td>{{ user.nom }}</td>
</tr>
<tr>
<th>Prenom</th>
<td>{{ user.prenom }}</td>
</tr>
<tr>
<th>Adresse</th>
<td>{{ user.adresse }}</td>
</tr>
{% if user.isMedecin %}
<tr>
<th>Clinique</th>
<td>{{ user.nomClinique }}</td>
</tr>
<tr>
<th>Adresse de la Clinique</th>
<td>{{ user.cliniqueAdresse }}</td>
</tr>
<tr>
<th>Spécialité</th>
<td>{% for Spe in user.Specialite %}
          {{ Spe.libelle}}
          {% endfor %}</td>
</tr>
<tr>
<th>Nombres de Favoris</th>
<td>{{ user.favoris }}
{{ user.favoris == null ? 0 : ""}}
</td>
</tr>
{% endif %}
</tbody>
</table>
{% if app.user %}
{% if app.user.id == user.id %}
<div class="d-flex justify-content-center">
<a href="{{ path('app_user_edit', {'id': user.id}) }}" class="btn btn-primary mr-2" style="margin-right: 1rem;">Edit</a>
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
<button class="btn btn-danger">Delete</button>
</form>
{% else %}
{% if user.isMedecin %}
<div class="d-flex justify-content-center">
{% if app.user.rdv == 0 %}
<a href="/rendezvous/new" class="btn btn-primary mr-2" style="margin-right: 1rem;">Prendre Rendez-vous</a>
{% else %}
<a href="#" class="btn btn-danger mr-2" style="margin-right: 1rem;">Supprimer Rendez-vous</a>
{% endif %}
<a href="/commentaire/new" class="btn btn-info mr-2" style="margin-right: 1rem;">Laissez votre avis</a>
<form method="post" action="{{ path('app_user_add_favoris', {'id': user.id}) }}">
  <input type="hidden" name="_token" value="{{ csrf_token('add_favoris' ~ user.id) }}">
  <button type="submit" class="btn btn-warning">Favoris</button>
</form>
</div>
{% endif %}
{% endif %}
{% endif %}
{% if is_granted('ROLE_ADMIN') %}
<div class="d-flex justify-content-center">
<a href="{{ path('app_user_edit', {'id': user.id}) }}" class="btn btn-primary mr-2" style="margin-right: 1rem;">Edit</a>
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
<button class="btn btn-danger">Delete</button>
</form>
{% endif %}
</div>
</div>
</div>
</div>

{% if user.isMedecin %}
<div class="container mt-5">
<div class="card">
<div class="card-header bg-primary text-white text-center py-3">
<h3>Commentaires</h3>
</div>
<div class="card-body">
<table class="table table-striped">
<tbody>
{% for Com in user.Commentaire %}
  <th>{{ Com.libelle}}</th>
  <td>{{ Com.description }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
{% endif %}
<script type="text/javascript">
const link = document.querySelector("a.btn.btn-primary.mr-2");

let rdv = 0;

if (rdv === 1) {
  link.setAttribute("href", "#");
}

link.addEventListener("click", function() {
  rdv = 1;
  link.setAttribute("href", "/rendezvous/new");
  link.setAttribute("class", "btn btn-danger mr-2");
  link.innerHTML = "Supprimer Rendez-vous";
});

</script>
{% endblock %}